---
- name: Ping www.google.com from Cisco devices
  hosts: JNET_Network
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Ping google.com
      cisco.ios.ios_command:
        commands:
          - ping www.google.com repeat 5
      register: ping_result

    - name: Show ping results
      debug:
        var: ping_result.stdout_lines
