---
- name: Execute commands on Cisco Devices in Lab Network
  hosts: AFJS, 55.55.55.2, 55.55.55.3, 55.55.55.4, 55.55.55.5
  gather_facts: no

  tasks:
    - name: Ping Google
      ios_command:
        commands: 
          - ping www.google.com
      register: command_output

    - name: Print command output
      debug:
        var: command_output.stdout_lines
