---
- name: Ping www.google.com from Cisco devices
  hosts: 55.55.55.2, 55.55.55.3, 55.55.55.4, 55.55.55.5
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Ping google.com
      cisco.ios.ios_command:
        commands:
          - ping www.google.com repeat 5
      register: ping_result

    - name: Show ping results
      debug:
        var: ping_result.stdout_lines
