---
- name: Ping www.google.com from Cisco devices
  hosts: JNET_Network
  gather_facts: false

  tasks:
    - name: Test reachability to 198.51.100.251 using default vrf
      cisco.ios.ios_ping:
        dest: www.google.com
        register: ping_result

    - name: Show ping results
      debug:
        var: ping_result.stdout_lines
