---

- name: Cisco show version example
  hosts: JNET_Network
  gather_facts: false

  tasks:
    - name: run show version on the routers
      ios_command:
        commands: ping www.google.com
      register: output

    - name: print output
      debug:
        var: output.stdout_lines
