---
- name: Join Red Hat Linux server to AD domain
  hosts: Gold_Systems
  become: yes
  vars:
    ad_domain: lab-dc-01.bizzy-lab.com
    ad_user: "{{ lookup('env', 'DOMAIN_JOIN_USER') }}"
    ad_password: "{{ lookup('env', 'DOMAIN_JOIN_PASSWORD') }}"

  tasks:
    - name: Install required packages
      package:
        name:
          - realmd
          - sssd
          - samba-common
          - samba-common-tools
          - oddjob
          - oddjob-mkhomedir
          - adcli
          - chrony
        state: present

    - name: Ensure chrony is started and enabled
      service:
        name: chronyd
        state: started
        enabled: yes

    - name: Configure chrony for time synchronization
      blockinfile:
        path: /etc/chrony.conf
        block: |
          server {{ ad_domain }} iburst
          server time.windows.com iburst

    - name: Restart chrony service
      service:
        name: chronyd
        state: restarted

    - name: Check if FIPS mode is enabled
      command: cat /proc/sys/crypto/fips_enabled
      register: fips_check
      changed_when: false
      failed_when: false

    - name: Warn if FIPS mode is not enabled
      debug:
        msg: "Warning: FIPS mode is not enabled on this system."
      when: fips_check.stdout != '1'

    - name: Check DNS resolution for the AD domain
      command: nslookup {{ ad_domain }}
      register: nslookup_result
      ignore_errors: yes

    - name: Fail if DNS resolution fails
      fail:
        msg: "DNS resolution for the AD domain failed: {{ nslookup_result.stderr }}"
      when: nslookup_result.rc != 0

    - name: Discover the AD domain
      command: realm discover {{ ad_domain }}
      register: realm_discover_result
      ignore_errors: yes

    - name: Fail if realm discover fails
      fail:
        msg: "Unable to discover the AD domain: {{ realm_discover_result.stderr }}"
      when: realm_discover_result.rc != 0

    - name: Join the AD domain
      expect:
        command: realm join -U {{ ad_user }} {{ ad_domain }}
        responses:
          Password for *: "{{ ad_password }}"
      register: join_result
      timeout: 120  # Increase the timeout to 120 seconds

    - name: Check the AD join result
      fail:
        msg: "Unable to join the AD domain: {{ join_result.stderr }}"
      when: join_result.rc != 0

    - name: Restart SSSD service
      service:
        name: sssd
        state: restarted
        enabled: yes
        
    - name: Validate the AD join using realm list
      command: realm list
      register: realm_list_result
      ignore_errors: yes

    - name: Check the realm list result for domain name
      command: grep 'domain_name: bizzy-lab.com' realm list
      register: domain_name_result
      ignore_errors: yes

    - name: Validate the /etc/sssd/sssd.conf file for domain configuration
      command: grep 'bizzy-lab.com' /etc/sssd/sssd.conf
      register: sssd_conf_result
      ignore_errors: yes

    - name: Check the sssd.conf result for domain configuration
      fail:
        msg: "AD join validation failed: Domain configuration not found in /etc/sssd/sssd.conf"
      when: sssd_conf_result.rc != 0
