---
- name: Join Red Hat Linux server to AD domain
  hosts: redhat_servers
  become: yes
  vars:
    ad_domain: bizzy-lab.com
    ad_user: "{{ ansible_user }}"
    ad_password: "{{ ansible_password }}"

  tasks:
  - name: Install required packages
    package:
      name:
        - realmd
        - sssd
      state: present

  - name: Check if FIPS mode is enabled
    command: cat /proc/sys/crypto/fips_enabled
    register: fips_check
    changed_when: false
    failed_when: false

  - name: Warn if FIPS mode is not enabled
    debug:
      msg: "Warning: FIPS mode is not enabled on this system."
    when: fips_check.stdout != '1'

  - name: Join the AD domain
    command: realm join --user={{ ad_user }} {{ ad_domain }} --install=/ -U {{ ad_user }}%{{ ad_password }}
    register: join_result
    ignore_errors: yes

  - name: Check the AD join result
    fail:
      msg: "Unable to join the AD domain, {{ join_result.stderr }}"
    when: join_result.rc != 0

  - name: Restart SSSD service
    service:
      name: sssd
      state: restarted
      enabled: yes

  - name: Validate the AD join
    command: getent passwd {{ ad_user }}
    register: validate_result
    ignore_errors: yes

  - name: Check the validation result
    fail:
      msg: "AD join validation failed, {{ validate_result.stderr }}"
    when: validate_result.rc != 0
