---
- name: Add a Banner
  hosts: ios
  tasks:
  - name: CREATE NEW BANNER
    ios_config:
      authorize: yes
      lines:
        - banner motd ^This is my banner^
  - name: SHOW RUN | B BANNER
    ios_command:
      authorize: yes
      commands:
        - show run | b banner
    register: banner
  - debug: var=banner.stdout_lines
