---
- name: Start ERSA Service
  hosts: ERSA_Sensornodes
  become: yes
  tasks:
    - name: Start ERSA service
      ansible.builtin.systemd:
        name: ersa
        state: started
        enabled: yes
